import Navbar from "@/components/navbar/Navbar";
import { Provider } from "@/components/themeswitch/Provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flux Design Systems",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="relative flex flex-col">
            <Navbar />
            <main className="relative container mx-auto max-w-7xl z-10 px-6 min-h-[calc(100vh_-_64px_-_108px)] mb-12 flex-grow">
              <div className="grid grid-cols-12">{children}</div>
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
